"""add file path to documents

Revision ID: 7db7ca6bd3b7
Revises: f96fc3b6cd15
Create Date: 2026-09-21 12:38:53.310346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db7ca6bd3b7'
down_revision: Union[str, Sequence[str], None] = 'f96fc3b6cd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
