"""add unique constraint on chunk document_id and chunk_index

Revision ID: 7f0bf2d8c83c
Revises: 739b5589800a
Create Date: 2026-09-21 14:59:53.134813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0bf2d8c83c'
down_revision: Union[str, Sequence[str], None] = '739b5589800a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk_index', 'chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_index', 'chunks', type_='unique')
    # ### end Alembic commands ###
